### ISSUE TITLE
Installation and using with Visual Studio Code or Visual Studio 2019

### ISSUE THREAD

**Issue by pierrenavarra** [openE57/openE57#20]
Hi,
Thx for the lib.
I'm trying make a simple reader of e57 files and I'd like to know if it could be possible to  to have a detailed explanation of the installation of the library so that I can use it under VSCode?
Installation steps?
Thank you

**Comment by madduci** [comment]
Hi

You're welcome and thanks for the message.
Actually the library can be installed using CMake itself or if you use
conan.io, you have first to install it with conan, so you can later build
on top of it (see the README.md file for the instructions).

**Comment by pierrenavarra** [comment]
Hi Madduci and thx forn your answer.
Do you mean I have to use CMAKE or Conan to build OpenE57 library?
I've got some V# projects and I jsut need to add dll references but this is not the procedure with the OpenE57 library?
When I want to use #include I also need to add what? The result of the buidling with CMAKE? How it works exactly?

**Comment by madduci** [comment]
You're almost there.

First build everything with cmake (or with Conan, it is an optional step,
highly suggested).

Once you've it's built, you can install install (with CMake itself) and it
will copy the header files and the Library file (statically compiled,
unfortunately it is actually not possible to build a shared library, as in
the original reference code).

From there, you can point your project to use those files.

Il ven 28 gen 2022, 15:23 pierrenavarra ***@***.***> ha
scritto:

**Comment by pierrenavarra** [comment]
Hi, I've installed Git and cmake and into PowerShell I follow your instructions : 
```

git clone https://github.com/madduci/openE57.git
cd open57
md build\windows && cd build\windows
conan install ..\.. --build=missing
cmake ..\.. -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release
cmake --install . --config Release
```

Now, I've got this in my directory : 
![screenshot_165](https://user-images.githubusercontent.com/54843266/151576662-ed788f15-d136-4905-b44b-035fe1997ce9.png)

But now, what I need to do ?
Sorry fir that Madduci , I ask you a lot because I don't know anything about it, thank you for taking the time

**Comment by madduci** [comment]
Oh what I see in your folder isn't correct at all, especially with all
those generated folders. You have probably pasted the commands directly in
Powershell from GitHub?

Can you please run these commands from the VS Developer Command Prompt
(search in your Start Menu/Visual Studio)?



Il ven 28 gen 2022, 16:43 pierrenavarra ***@***.***> ha
scritto:

**Comment by pierrenavarra** [comment]
Hi madduci.
Thx for your great answer!
You're right, I ran th commands in PowerShell not in VS Developer Command Prompt
Now, in c\openE57 I've got this :
![screenshot_168](https://user-images.githubusercontent.com/54843266/151753538-b91b0400-a9cb-4247-add5-5028b27fe884.png)
![screenshot_169](https://user-images.githubusercontent.com/54843266/151753548-345c9955-db6b-47fe-9f4b-46bd4beb616d.png)

Now, the next question is, how to configure my OpenE57 solution to make a simple HelloWorld openning a simple E57 file?

Thx for your patience and understanding.

**Comment by pierrenavarra** [comment]
Hi, When I create e OpenE57 project, with this code source : 
```

/*** HelloWorld.cpp example: the basics */
#include <iostream>
#include <D:\TEMPORAIRE\DEV\CPP\E57\E57\ext\openE57\include\openE57/openE57.h>

using namespace e57;
using namespace std;
```

I've got this message into my terminal of Vstudio

```
1>------ Début de la génération : Projet : E57, Configuration : Debug Win32 ------
1>MSVCRTD.lib(exe_main.obj) : error LNK2019: symbole externe non résolu _main référencé dans la fonction "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>D:\TEMPORAIRE\DEV\CPP\E57\E57\Debug\E57.exe : fatal error LNK1120: 1 externes non résolus
1>Génération du projet "E57.vcxproj" terminée -- ÉCHEC.
```

**Comment by madduci** [comment]
I'm glad you were able to go further with your project.

> Message ID: ***@***.***>
>

Concerning the linking of the openE57 library in your project, I would
suggest you to check the examples folders or you might leave this setup
phase to Conan.

Create a conanfile.txt where is written:

```txt
[requires]
openE57/1.5.1

[generators]
cmake_find_package
```

And in your CMakeLists.txt  you add the FindPackage entry (see the Conan
and CMake documentations for it)

**Comment by pierrenavarra** [comment]
Wow...I do not understand....Sorry

**Comment by madduci** [comment]
I've made a quick and dirty project showing how to integrate openE57 externally. I hope it helps.

Please read the README instructions there.

https://github.com/openE57/openE57-sample-project
