### ISSUE TITLE
Error on compiling simple Read E57

### ISSUE THREAD

**Issue by pierrenavarra** [openE57/openE57#22]
Hi,
I've got a simple C++ code wich just read a E57 file
I've got those errors : 
`1>openE57.obj : error LNK2019: symbole externe non résolu "public: __cdecl e57::ImageFile::ImageFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0ImageFile@e57@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z) référencé dans la fonction main
1>openE57.obj : error LNK2019: symbole externe non résolu "public: class e57::StructureNode __cdecl e57::ImageFile::root(void)const " (?root@ImageFile@e57@@QEBA?AVStructureNode@2@XZ) référencé dans la fonction main
1>openE57.obj : error LNK2019: symbole externe non résolu "public: void __cdecl e57::ImageFile::close(void)" (?close@ImageFile@e57@@QEAAXXZ) référencé dans la fonction main
1>D:\TEMPORAIRE\DEV\CPP\openE57\VS2019\openE57\x64\Debug\openE57.exe : fatal error LNK1120: 3 externes non résolus
`
**Maybe I've to add lib?**

Here is my code
`#include <iostream>
#include "ext/include/openE57/openE57.h"
using namespace e57;
using namespace std;

int main(int /*argc*/, char** /*argv*/)
{
  try
  {
    /// Read file from disk
    ImageFile imf("E57\\R00-Commun- COMBARY_111.e57", "r");
    StructureNode root = imf.root();
  
    imf.close();
  }
  catch (E57Exception& ex)
  {
    ex.report(__FILE__, __LINE__, __FUNCTION__);
    return -1;
  }
  catch (std::exception& ex)
  {
    cerr << "Got an std::exception, what=" << ex.what() << endl;
    return -1;
  }
  catch (...)
  {
    cerr << "Got an unknown exception" << endl;
    return -1;
  }
  return 0;
}`

**Comment by madduci** [comment]
Hi

thank you for the issue.

I've updated the project and the sample project. Please follow the new instructions and try it again. Hope it helps

**Comment by pierrenavarra** [comment]
Hi madduci
And thx for updated the project.
So, I need to delete my OpenE57 directory and do those commands : 

`git clone https://github.com/madduci/openE57.git
cd open57
conan create . --build=missing`

And, create a new project into VisuaStudio?
Am I correct?
Do I have to add libraries into my project properties?

Anyway, many thx!
Hop it will works!!

**Comment by pierrenavarra** [comment]
Hi maducci.
I found the openE57_exemple.sln
But, When I generate the openE57_example, I've got those errors 

`2>openE57.lib(openE57.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in example.obj
2>openE57.lib(openE57.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in example.obj
2>openE57.lib(openE57Impl.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in example.obj
2>openE57.lib(openE57Impl.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in example.obj
2>xerces-c_3.lib(XMemory.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in example.obj
2>xerces-c_3.lib(XMemory.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in example.obj`

**Comment by madduci** [comment]
You should select Release from Visual Studio's drop-down menu, instead of
Debug

Il gio 10 feb 2022, 18:14 pierrenavarra ***@***.***> ha
scritto:

**Comment by madduci** [comment]
Then you need to compile the openE57 package in debug mode as well. Please
refer to official Conan documentation -
https://docs.conan.io/en/latest/using_packages/debugging.html)

**Comment by madduci** [comment]
You are welcome!
